---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ttwings.
--- DateTime: 2018/11/29 22:45
---
--- 添加例子系统测试
--- 练习canvas用法

local p = {}

function p.getBubble(size)
    local bubble = love.graphics.newCanvas(size,size)
    love.graphics.setCanvas(bubble)
    love.graphics.setColor(1,1,1,1)
    love.graphics.ellipse("fill",size/2,size/2,size/2,size/4)
    love.graphics.setCanvas()
    return bubble
end

function p.getBubbleTrail(image)
    local particle_system = love.graphics.newParticleSystem(image,50)
    particle_system:setParticleLifetime(1,1)
    particle_system:setSpeed(-50)
    particle_system:setColors(1,1,1,0.8,1,1,1,0.5,1,1,1,0)
    particle_system:setSizes(0.2,0.8)
    return particle_system
end

function p.getBlast(size)
    local blast = love.graphics.newCanvas(size,size)
    love.graphics.setCanvas(blast)
    love.graphics.setColor(1,1,1,1)
    love.graphics.circle("fill",size/2,size/2,size/2)
    love.graphics.setCanvas()
    return blast
end

function p.getExplosion(image)
    local particle_system = love.graphics.newParticleSystem(image,30)
    particle_system:setParticleLifetime(0.5,0.5)
    particle_system:setLinearAcceleration(-100,-100,100,100)
    particle_system:setColors(1,1,0,1,1,0.5,0.2,1,0.15,0.15,0.15,0)
    particle_system:setSizes(0.5,0.5)
    return particle_system
end

return p