---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/15 上午12:18
---

--- @class BoostEffect : NewGameObject

BoostEffect = NewGameObject:extend()

function BoostEffect:new(area,x,y,opts)
    BoostEffect.super.new(self,area,x,y,opts)

end