---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/15 上午12:18
---

--- @class BoostEffect : NewGameObject

BoostEffect = NewGameObject:extend()

function BoostEffect:new(area,x,y,opts)
    BoostEffect.super.new(self,area,x,y,opts)
    self.w = opts.w or 12
    self.h = opts.h or 12
    self.current_color = Color.default
    self.timer:after(0.2,function ()
        self.current_color = self.color
        self.timer:after(0.35,function ()
            self.dead = true
        end)
    end)

    self.visible = true
    self.timer:after(0.2,function ()
        self.timer:every(0.05,function () self.visible = not self.visible end,6)
        self.timer:after(0.35,function () self.visible = true end)
    end)

    if not self.visible then return end
    love.graphics.setColor(self.current_color)
    draft:rhombus(self.x,self.y,1.34 * self.w,1.34 * self.h,'fill')
    draft:rhombus(self.x,self.y,2 * self.w, 2* self.h,'line')
    love.graphics.setColor(Color.default)

    self.sx,self.sy = 1,1
    self.timer:tween(0.35,self,{sx = 2,sy = 2},'in-out-cubic')
end

function BoostEffect:draw()
    BoostEffect.super.draw(self)
    draft:rhombus(self.x,self.y,self.sx * 1.34 * self.w,self.sy * 1.34 * self.h,'fill')
    draft:rhombus(self.x,self.y,self.sx * 2 * self.w, self.sy * 2* self.h,'line')
end