---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/20 下午11:53
---

--- @class Director : Object

Director = Object:extend()

function Director:new(stage)
    self.stage = stage
    self.difficulty = 1
    self.round_duration = 22
    self.round_time = 0
    self.difficulty_to_point = {}
    self.difficulty_to_point[1] = 16
    for i = 2, 1024,4 do
        self.difficulty_to_point[i] = self.difficulty_to_point[i - 1] + 8
        self.difficulty_to_point[i + 1] = self.difficulty_to_point[i]
        self.difficulty_to_point[i + 2] = self.difficulty_to_point[i + 1]/1.5
        self.difficulty_to_point[i + 3] = self.difficulty_to_point[i + 2] * 2
    end

    self.enemy_to_point = {
        ['Rock'] = 1,
        ['Shooter'] = 2
    }
end

function Director:update(dt)
    self.round_time = self.round_time + dt
    if self.round_time > self.round_duration then
        self.round_time = 0
        self.difficulty = self.difficulty + 1
        self:setEnemySpawnForThisRound()
    end
end

function Director:setEnemySpawnForThisRound()

end