---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/16 下午12:46
---

--- @class EnemyDeathEffect

EnemyDeathEffect = GameObject:extend()

function EnemyDeathEffect:new(area,x,y,opts)
    EnemyDeathEffect.super.new(self,area,x,y,opts)
    self.w = opts.w or 10
    self.h = opts.h or 10
    self.first = true
    self.timer:after(0.1 ,function ()
        self.first = false
        self.second = true
        self.timer:after(0.15,function ()
            self.second = false
            self.dead = true
        end)
    end)
end

function EnemyDeathEffect:draw()
    if self.first then love.graphics.setColor(Color.default)
    elseif self.second then love.graphics.setColor(self.color) end
    love.graphics.rectangle('fill',self.x - self.w/2,self.y- self.w/2,self.w,self.w)
end