---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/30 下午11:38
---
require("objects.NewGameObject")

ExplodeParticle = GameObject:extend()

function ExplodeParticle:new(area,x,y,opts)
    ExplodeParticle.super.new(self,area,x,y,opts)

    self.color = opts.color or Color.default
    self.r = random(0, 2*math.pi)
    self.s = opts.s or random(2,3)
    self.v = opts.v or random(75,150)
    self.line_width = 2
    self.timer:tween(opts.d or random(0.3,0.5), self,{s = 0,v=0,line_width = 0},
    'linear',function () self.dead = true end )
end

function ExplodeParticle:draw()
    p_print("explode")
    pushRote(self.x,self.y,self.r)
    love.graphics.setLineWidth(self.line_width)
    love.graphics.setColor(self.color)
    love.graphics.line(self.x - self.s ,self.y ,self.x - self.s, self.y)
    love.graphics.setColor(1,1,1,1)
    love.graphics.setLineWidth(1)
    love.graphics.pop()
end