---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/15 下午2:08
---

--- @class HpEffect : NewGameObject
HpEffect = NewGameObject:extend()

function HpEffect:new(area, x, y, opts)
    HpEffect.super.new(self,area,x,y,opts)
    self.w = opts.w or 12
    self.h = opts.h or 12
    self.current_color = Color.hp
    self.timer:after(0.2,function ()
        self.current_color = self.color
        self.timer:after(0.35,function ()
            self.dead = true
        end)
    end)

    self.visible = true
    self.timer:after(0.2,function ()
        self.timer:every(0.05,function () self.visible = not self.visible end,6)
        self.timer:after(0.35,function () self.visible = true end)
    end)

    self.sx,self.sy = 1,1
    self.timer:tween(0.35,self,{sx = 2,sy = 2},'in-out-cubic')
end

function HpEffect:draw()
    if not self.visible then return end
    love.graphics.setColor(self.current_color)
    draft:circle(self.x,self.y,self.sx * 1.5 * self.w,self.y * 1.5 * self.h, 'line')
    love.graphics.setColor(Color.hp)
    draft:rectangle(self.x,self.y,self.sx * 0.3 * self.w,self.sy * 0.9 * self.h, 'fill')
    draft:rectangle(self.x,self.y,self.sx * 0.9 * self.w,self.sy * 0.3 * self.h, 'fill')
    love.graphics.setColor(Color.default)

end