---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/14 上午12:09
---
--- @class InfoText : NewGameObject
--- @param area Area
--- @param x number
--- @param y number
--- @param opts table
--- @field text string
--- @field font Font
--- @field color table
--- @field sx number
--- @field sy number
--- @field depth number
--- @field characters table
--- @field visible boolean

InfoText = NewGameObject:extend()

function InfoText:new(area,x,y,opts)
    InfoText.super.new(self,area,x,y,opts)
    self.text = opts.text or ""
    self.font = Fonts.unifont
    self.color = opts.color or {1,0,0}
    self.sx = opts.sx or 1
    self.sy = opts.sy or 1
    self.depth = 80
    self.characters = {}
    self.visible = true

    self.background_colors = {}
    self.foreground_colors = {}

    for i = 1,#self.text,3 do
        table.insert(self.characters,self.text:sub(i,i+2))
    end
    self.timer:after(0.7,function ()
        self.timer:every(0.05,function () self.visible = not self.visible end)
        self.timer:after(0.35,function () self.visible = true end)

        self.timer:every(0.035,function ()
            local random_characters = "0123456789~!@#$%^&*()_+-=abcdefghijklmnopqrstuvwxyz"
            for i,character in ipairs(self.characters) do
                if math.random(1,20) <= 1 then
                    local r = love.math.random(1,#random_characters)
                    self.characters[i] = random_characters:sub(r,r)
                else
                    self.characters[i] = character
                end
            end
        end)
    end)
    self.timer:after(1.10,function ()
        self:die()
    end)
end
--- TODO complete
function InfoText:update(dt)
    if self.timer then self.timer:update(dt) end
end

function InfoText:draw()
    love.graphics.setFont(self.font)
    for i = 1, #self.characters do
        local width = 0
        if i>1 then
            for j = 1,i-1 do
                width = width + self.font:getWidth(self.characters[j])
            end
        end
---- TODO random color ,#7
        love.graphics.setColor(self.color)
        if self.visible then
            love.graphics.print(self.characters[i],self.x + width,self.y,
                    0,self.sx,self.sy,0,self.font:getHeight()/2)
        end

    end
end

function InfoText:die()
    self.dead = true
end