---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/29 下午11:10
---

--- @class NewGameObject : GameObject
--- @param area Area
--- @param x number
--- @param y number
--- @field extend fun()
require("objects.GameObject")

NewGameObject = GameObject:extend()

--- @type fun(area:Area,x:number,y:number,opts:table)

function NewGameObject:new(area,x,y,opts)
    NewGameObject.super.new(self,area,x,y,opts)
end

--- @type fun(dt:number)
function NewGameObject:update(dt)
    NewGameObject.super.update(self,dt)
end
--- @type fun()
function NewGameObject:destroy()
    NewGameObject.super.destroy(self)
end

function NewGameObject:draw()
    NewGameObject.super.draw(self)
end
