---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 18-9-18 下午3:32
---

--- @class Node : Object

Node = Object:extend()

--- @param x number
--- @param y number
--- @field w number
--- @field h number
--- @field bought boolean
function Node:new(id,x,y)
    self.id = id
    self.x = x
    self.y = y
    self.w = 10
    self.h = self.w or 10
    self.bought = false
end


function Node:update(dt)
    local mx,my = camera:getMousePosition(sw * camera.scale,sh * camera.scale,0,0,sw * gw,sh * gh)
    mx,my = mx/sw,my/sh

    --local mx,my = love.mouse.getPosition()
    if  mx > self.x - self.w/2 and mx < self.x + self.w/2 and
        my > self.y - self.h/2 and my < self.y + self.h/2 then
        self.hot = true
    else
        self.hot = false
    end
    --- p_print(mx,my)
    --- bought
    if fn.any(bought_node_indexes,self.id) then
        self.bought = true
    else
        self.bought = false
    end

    if self.hot and skill_points.left > 0
            and skill_points.bought < skill_points.max and input:pressed("left_click") then
        if current_room:canNodeBeBought(self.id) then
            table.insert(bought_node_indexes,self.id)
            skill_points.bought = skill_points.bought + 1
            skill_points.left = skill_points.left - 1
        end
    end
end

function Node:draw()
    local r,g,b = unpack(Color.default)
    love.graphics.setColor(Color.background)
    love.graphics.circle('fill',self.x,self.y,self.w)
    if self.bought then
        love.graphics.setColor(r,g,b,1)
    else
        love.graphics.setColor(r,g,b,0.15)
    end
    if self.sharp then
        love.graphics[self.sharp]('line',self.x,self.y,self.w)
    else
        love.graphics.circle('line',self.x,self.y,self.w)
    end
    love.graphics.setColor(r,g,b,1)

end