---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/28 下午8:28
---

Player = GameObject:extend()

function Player:new(area,x,y,opts)
    Player.super.new(self, area, x, y, opts)
end

function Player:update(dt)
    Player.super.update(self,dt)
end

function Player:draw()
    love.graphics.circle('line',self.x,self.y,25)
end