---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/30 下午10:43
---

---@class Projectile

Projectile = NewGameObject:extend()

function Projectile:new(area,x,y,opts)
    Projectile.super.new(self,area,x,y,opts)
    self.s = opts.s or 2.5
    self.v = opts.v or 200

    self.collider = self.area.world:newCircleCollider(self.x,self.y,self.s)
    self.collider:setCollisionClass("Projectile")
    self.collider:setObject(self)
    self.collider:setLinearVelocity(self.v*math.cos(self.r),self.v*math.sin(self.r))
end

function Projectile:update(dt)
    Projectile.super.update(self,dt)
    self.collider:setLinearVelocity(self.v*math.cos(self.r),self.v*math.sin(self.r))
    if self.x < 0 then self:die() end
    if self.y < 0 then self:die() end
    if self.x > gw then self:die() end
    if self.y > gh then self:die() end
end

function Projectile:draw()
    Projectile.super.draw()
    pushRote(self.x,self.y,self.r - math.pi/4)
    love.graphics.circle('line',self.x,self.y,self.s)
    love.graphics.pop()
end

function Projectile:die()
    self.dead = true
    self.area:addObject('ProjectileDeathEffect',self.x,self.y,{color = Color.hp,w = 3*self.s})
end