---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 18-9-18 下午4:03
---
tree = {}
tree[1] = {x = 0, y = 0, links = {2}}
tree[2] = {x = 48, y = 0, stats = {'4% Increased HP', 'hp_multiplier', 0.04}, links = {3}}
tree[3] = {x = 96, y = 0, stats = {'6% Increased HP', 'hp_multiplier', 0.06}, links = {4}}
tree[4] = {x = 144, y = 0, stats = {'4% Increased HP', 'hp_multiplier', 0.04}}

local suit = require("lib.suit")
local ui_input = {text = "Hello"}
local chk = {text = "check"}
local slider = {value = 0.5,min = -2,max = 2}

--- @class SkillTree : GameObject

SkillTree = Object:extend()

function SkillTree:new()
    self.area = Area(self)
    self.tree = table.copy(tree)
    p_print(tree)
    self.nodes = {}
    self.lines = {}
    --self.timer = Timer()
    self.main_canvas = love.graphics.newCanvas(gw,gh)
    --camera.x = gw/2
    --camera.y = gh/2
    for id,node in ipairs(self.tree) do
        for _,linked_node_id in ipairs(node.links or {}) do
            table.insert(self.tree[linked_node_id],id)
        end
    end
    for id, node in ipairs(self.tree) do table.insert(self.nodes, Node(id, node.x, node.y)) end
    for id, node in ipairs(self.tree) do
        if node.links then
            for _, linked_node_id in ipairs(node.links) do
                table.insert(self.lines, Line(id, linked_node_id))
            end
        end
    end
end


function SkillTree:update(dt)
    for _, node in ipairs(self.nodes) do
        node:update(dt)
    end
    for _, line in ipairs(self.lines) do
        line:update(dt)
    end


    if love.mouse.isDown(1) then
        local mx,my = camera:getMousePosition(sw,sh,0,0,sw * gw,sh * gh)
        local dx,dy = mx - self.previous_mx,my - self.previous_my
        --- when camera scale, x,y position should / scale
        camera:move(-dx/sw,-dy/sh)
    end
    self.previous_mx,self.previous_my = camera:getMousePosition(sw,sh,0,0,sw * gw,sh * gh)

    if input:pressed("zoom_in") then
        timer:tween(0.2,camera,{scale = camera.scale + 0.4},'in-out-cubic')
    end
    if input:pressed("zoom_out") then
        timer:tween(0.2,camera,{scale = camera.scale - 0.4},'in-out-cubic')
    end

    --- suit test
    --suit.Label("技能点:" .. skill_points.left,gw - 100,0,100,20)
    suit.layout:reset(gw/2 - 40,gh - 40,20,20)
    apply = suit.Button("确定",suit.layout:row(50,30))
    cancel = suit.Button("取消", suit.layout:col())
    suit.Label("Apply",suit.layout:col())
    mx,my = love.mouse.getX(),love.mouse.getY()

    if apply.hovered then
        print("enter")
        suit.Label("Apply",suit.layout:col())
    end
    if apply.hit then
        print("Apply")
    end

    if suit.Button("Hover?",suit.layout:row(nil,40)).hovered then
        suit.Button("You Can See",{align = 'left',valign = 'top'},suit.layout:row(nil,50))
        suit.Button("But you cant touch!",{align = 'right',valign = 'bottom'},suit.layout:row())
    end
    --suit.ImageButton()
    suit.Checkbox(chk,{align = 'right'},suit.layout:row())
    suit.layout:push(suit.layout:row())
    suit.layout:padding(3)
    suit.Slider(slider,suit.layout:col(160,20))
    suit.Label(("%.02f"):format(slider.value),suit.layout:col(40))
    suit.layout:pop()


end


function SkillTree:draw()

    love.graphics.setCanvas(self.main_canvas)
    love.graphics.clear()
    local font = Fonts.unifont
    love.graphics.setFont(font)
    love.graphics.print({{1,0,0},"科技树"},gw*sw/2 - 20,0,0,sw,sh)
    camera:attach()
    --- sp
    love.graphics.setColor(Color.skill_point)
    if self.area then self.area:draw() end
    ---- draw line
    for _, line in ipairs(self.lines) do
        line:draw()
    end
    for _, node in ipairs(self.nodes) do
        node:draw()
    end
    --- draw node
    for _,node in ipairs(self.nodes) do
        if node.hot and tree[node.id].stats then
            local stats = tree[node.id].stats
            --- get max text width
            local max_text_width = 0
            for i=1,#stats,3 do
                if font:getWidth(stats[i]) > max_text_width then
                    max_text_width = font:getWidth(stats[i])
                end
            end
            --- draw rectangle
            local mx,my = camera:getMousePosition(sw*camera.scale,sh*camera.scale,0,0,sw * gw,sh * gh)
            --local mx,my = love.mouse.getPosition()
            mx,my = mx/sw,my/sh
            --p_print(mx,my)
            love.graphics.setColor(1,0,0,0.8)
            love.graphics.rectangle('fill',mx,my
            ,16 + max_text_width,font:getHeight() + #stats/3 * font:getHeight())
            --- draw text
            love.graphics.setColor(Color.default)
            for i = 1,#stats,3 do
                love.graphics.print(stats[i]
                ,math.floor(mx + 8),math.floor(my + font:getHeight()/2 + math.floor(i/3) * font:getHeight()))
            end
        end
    end
    camera:detach()
    love.graphics.print('科技 : ' .. skill_points.left,0,0)

    love.graphics.setColor(1,1,1)
    love.graphics.setCanvas()
    --love.graphics.setBlendMode('alpha','premultiplied')
    love.graphics.draw(self.main_canvas,0,0,0,sw,sh)

    love.graphics.print({{1,0,0},mx,{0,1,1},my},gw/2,gh/2)
    suit.draw()
end

function SkillTree:canNodeBeBought(id)
    for _,linked_node_id in ipairs(self.tree[id]) do
        if fn.any(bought_node_indexes,linked_node_id) then return true end
    end
end

function SkillTree:keypressed(key)
    p_print("key pressed")
    suit.keypressed(key)
end