---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/15 下午7:27
---

--- @class Sp : NewGameObject

Sp = NewGameObject:extend()

function Sp:new(area,x,y,opts)
    Sp.super.new(self,area,x,y,opts)
    local direction = table.random({-1,1})
    self.x = gw/2 + direction * (gw/2 + 48)
    self.y = random(48,gh - 48)
    self.w,self.h = 12,12
    self.collider = self.area.world:newRectangleCollider(self.x,self.y,self.w,self.h)
    self.collider:setCollisionClass("Collectable")
    self.collider:setObject(self)
    self.collider:setFixedRotation(false)
    --self.r = random(0,2 * math.pi)
    self.v = - direction * random(10,20)
    self.collider:setLinearVelocity(self.v,0)
    self.collider:applyAngularImpulse(random(-24,24))
end

function Sp:update(dt)
    Sp.super.update(self,dt)
    self.collider:setLinearVelocity(self.v,0)
end

function Sp:draw()
    love.graphics.setColor(Color.skill_point)
    pushRote(self.x,self.y,self.collider:getAngle())
    draft:rhombus(self.x,self.y,1.5 * self.w,1.5 * self.h, 'line')
    draft:rhombus(self.x,self.y,0.5 * self.w,0.5 * self.h, 'fill')
    love.graphics.pop()
    love.graphics.setColor(Color.default)
end

function Sp:die()
    self.dead = true
    self.area:addObject("SpEffect",self.x,self.y,{color = Color.skill_point})
    self.area:addObject("InfoText",self.x,self.y,{text="+SP",color = Color.skill_point})
end