---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/30 下午11:58
---

--- @class StageShop
--- @field world World
--- @field area Area

local suit = require("lib.suit")

StageShop = Object:extend()

function StageShop:new()
    self.area = Area(self)
    self.seller = {name = "seller",items = {},money = 10000,lv = 0,relationship = 0}
    self.buyer = {name = "buyer",items = {},money = 10000}
    self.items_to_buy = {}
    self.items_to_sell = {}
    self.items_to_buy_money = 0
    self.items_to_sell_money = 0
    --- 物品差价，即需要补充的部分，负值表示卖出物品的价值较高
    self.items_money_difference = self.items_to_buy_money - self.items_to_sell_money
    self.main_canvas = love.graphics.newCanvas(gw,gh)
end

local input = {text = ""}

function StageShop:update(dt)
    if self.area then self.area:update(dt) end
    --- suit update
    test = suit.Button("X",{font = font},gw * sw - 40,0,40,40)

    if test.hit then
        love.event.quit()
    end

    suit.layout:reset()
    suit.layout:row(48,48)
    local row_num = 8
    for i = 0, 100 do
        suit.Button("物品" .. i,i%row_num * 48 + 32,math.floor(i/row_num) * 48 + 32,40,40)
    end

    suit.Label("钱:" .. 10000,100,gh * sh - 60,100,40)

end

function StageShop:draw()
    love.graphics.setCanvas(self.main_canvas)
    love.graphics.clear()
    camera:attach(0,0,sw*gw,sh*gh)
    love.graphics.print("中文")
    if self.area then self.area:draw() end

    --- shop ui
    love.graphics.rectangle("line",1,1,gw/3 -1 ,gh - 2,8)
    love.graphics.rectangle("line",1 + gw/3,1,gw/3 -1,gh - 2,8)
    love.graphics.rectangle("line",1 + gw * 2/3,1,gw/3 - 1,gh - 2,8)

    camera:detach()
    love.graphics.setCanvas()
    love.graphics.setColor(255,255,255,255)
    love.graphics.setBlendMode('alpha','premultiplied')
    love.graphics.draw(self.main_canvas,0,0,0,3,3)
    love.graphics.setBlendMode('alpha')
    ---- suit gui
    suit.draw()

end

function StageShop:destroy()
    if self.area then
        self.area:destroy()
        self.area = nil
    end
end

function StageShop:finished()
    timer:after(1,function ()
        gotoRoom("Stage","Stage")
    end)
end