---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/20 下午11:05
---

--- @class TargetParticle : NewGameObject

TargetParticle = NewGameObject:extend()

function TargetParticle:new(area,x,y,opts)
    TargetParticle.super.new(self,area,x,y,opts)
    self.r = opts.r or random(2,3)
    self.timer:tween(self.d or random(0.1,0.3),self,
            {r = 0,x = self.target_x,y = self.target_y},'out-cubic',function () self.dead = true end)
end

function TargetParticle:draw()
    TargetParticle.super.draw(self)
    love.graphics.setColor(self.color)
    draft:rhombus(self.x,self.y,self.r * 2,self.r * 2,'fill')
    love.graphics.setColor(Color.default)
end