---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/3 下午11:15
---

TickEffect = GameObject:extend()

function TickEffect:new(area,x,y,opts)
    TickEffect.super.new(self,area,x,y,opts)
    self.w = 48
    self.h = 32
    self.y_offset = 32
    self.timer:tween(0.13,self,{h=0},"in-out-cubic",function ()self.dead = true end)
end

--function TickEffect:update(dt)
--    if self.parent then self.x,self.y = self.parent.x,self.parent.y end
--end

function TickEffect:draw()
    love.graphics.circle("fill",self.x,self.y,self.w)
end