---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/3 下午11:35
---
--- @class TrailParticle : GameObject
--- @param area Area
--- @param opts Table
TrailParticle = GameObject:extend()

function TrailParticle:new(area,x,y,opts)
    TrailParticle.super.new(self,area,x,y,opts)
    self.r = opts.r or random(4,6)
    self.color = opts.color or Color.default
    self.timer:tween(opts.d or random(0.3,0.5),self,{r=0},"linear",
    function () self.dead = true end)
end

function TrailParticle:draw()
    TrailParticle.super.draw()
    love.graphics.setColor(self.color)
    love.graphics.circle("fill",self.x,self.y,self.r)
    love.graphics.setColor(Color.default)
end
