---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/15 下午11:58
---
--- abbreviation 缩写

---
attacks = {
    ["Neutral"] = {cooldown = 0.24, ammo = 0, abbreviation = "N", color = Color.default },
    ["Double"]  = {cooldown = 0.32, ammo = 2, abbreviation = "2", color = Color.ammo },
    ['Triple']  = {cooldown = 0.32, ammo = 3, abbreviation = '3', color = Color.boost},
    ['Rapid']   = {cooldown = 0.12, ammo = 1, abbreviation = 'R', color = Color.default},
    ['Spread']  = {cooldown = 0.16, ammo = 1, abbreviation = 'S', color = Color.default},
    ['Back']    = {cooldown = 0.32, ammo = 2, abbreviation = 'B', color = Color.skill_point},
    ['Side']    = {cooldown = 0.32, ammo = 3, abbreviation = 'Si', color = Color.boost},
    ['Blast']   = {cooldown = 0.5,  ammo = 5, abbreviation = 'Si', color = Color.hp},
}