---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/9/15 下午11:58

------
Fonts = {}
Fonts.unifont = love.graphics.newFont("assets/font/unifont.ttf")
---

Color = {}
Color.default = {1,1,1}
Color.background = {22/256,22/256,22/256}
Color.ammo = {123/256,200/256,164/256}
Color.boost = {76/256,195/256,217/256}
Color.hp = {241/256,103/256,69/256}
Color.skill_point = {255/256,198/256,93/256}
Color.trail_color = {0,0,1}
--- abbreviation 缩写

---
attacks = {
    ["Neutral"] = {cooldown = 0.24, ammo = 0, abbreviation = "Ne", speed = 200, color = Color.default },
    ["Double"]  = {cooldown = 0.32, ammo = 2, abbreviation = "Do", speed = 200, color = Color.ammo },
    ['Triple']  = {cooldown = 0.32, ammo = 3, abbreviation = 'Tr', speed = 200, color = Color.boost},
    ['Rapid']   = {cooldown = 0.12, ammo = 1, abbreviation = 'Ra', speed = 200, color = Color.default},
    ['Spread']  = {cooldown = 0.16, ammo = 1, abbreviation = 'Sp', speed = 200, color = Color.default},
    ['Back']    = {cooldown = 0.32, ammo = 2, abbreviation = 'Ba', speed = 200, color = Color.skill_point},
    ['Side']    = {cooldown = 0.32, ammo = 3, abbreviation = 'Si', speed = 200, color = Color.boost},
    ['Blast']   = {cooldown = 0.66, ammo = 5, abbreviation = 'Bl', speed = 600, color = Color.hp},
}

attacks_name = {"Neutral","Double","Triple","Rapid","Spread","Back","Side","Blast"}

score = {}
---- skill tree
--- @type table
tree = {}
tree[1] = {x = 0, y = 0, links = {2}}
tree[2] = {x = 48, y = 0, stats = {'4% Increased HP', 'hp_multiplier', 0.04}, links = {3}}
tree[3] = {x = 96, y = 0, stats = {'6% Increased HP', 'hp_multiplier', 0.06}, links = {4}}
tree[4] = {x = 144, y = 0, stats = {'4% Increased HP', 'hp_multiplier', 0.04}}

skill_points = {}
skill_points.left = 10
skill_points.max = 1000
skill_points.bought = 0

bought_node_indexes = {1}

achievements = {}
achievements['10k Fighter'] = true

first_run_ever = true

